apiVersion: apps/v1
kind: Deployment
metadata:
  name: drlm-core
  labels:
    srv: drlm3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drlm-core
  template:
    metadata:
      labels:
        app: drlm-core
        srv: drlm3
    spec:
      containers:
      - name: drlm-core
        image: didacog/drlm-core:0.0.6
        volumeMounts:
          - name: drlm-core-toml
            mountPath: "/etc/drlm"
            readOnly: false
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 50051
      volumes:
        - name: drlm-core-toml
          secret:
            secretName: drlm-core-toml
            items:
            - key: drlm-core.toml
              path: core.toml

---

apiVersion: v1
kind: Service
metadata:
  name: drlm-core
  labels:
    app: drlm-core
    srv: drlm3
spec:
  type: NodePort
  selector:
    app: drlm-core
  ports:
  - port: 50051
    protocol: TCP
    targetPort: 50051
    nodePort: 30051
