apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  labels:
    srv: drlm3
spec:
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
        srv: drlm3
    spec:
      containers:
      - name: mariadb
        image: mariadb:10.3
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: drlm3db
          - name: MYSQL_DATABASE
            value: drlm3
          - name: MYSQL_USER
            value: drlm3
          - name: MYSQL_PASSWORD
            value: drlm3db

---

apiVersion: v1
kind: Service
metadata:
  name: mariadb
  labels:
    app: mariadb
    srv: drlm3
spec:
  selector:
    app: mariadb
  ports:
  - port: 3306
