apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  srv: drlm3
spec:
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
        srv: drlm3
    spec:
      containers:
      - name: minio
        image: minio/minio
        volumeMounts:
        - name: minio-certs
          mountPath: ".minio/certs"
          readOnly: true
        command: 
          - minio
          - server
          - --address
          - ":9443"
          - .minio/data
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 9443
        env:
          - name: MINIO_ACCESS_KEY
            value: drlm3minio
          - name: MINIO_SECRET_KEY
            value: drlm3minio
      volumes:
      - name: minio-certs
        secret:
        secretName: minio-key
        items:
        - key: minio-key
          path: minio.key
        secretName: minio-cert
        items:
        - key: minio-cert
          path: minio.cert


---

apiVersion: v1
kind: Service
metadata:
  name: minio
  labels:
    app: minio
    srv: drlm3
spec:
  type: NodePort
  selector:
    app: minio
  ports:
  - port: 9443
    protocol: TCP
    targetPort: 9443
    nodePort: 50052
