apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
spec:
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: minio/minio
        command: 
          - minio
          - server
          - --address
          - ":9443"
          - .minio/data
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 9443
        env:
          - name: MINIO_ACCESS_KEY
            value: drlm3minio
          - name: MINIO_SECRET_KEY
            value: drlm3minio

---

apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  selector:
    app: minio
  ports:
  - port: 9443
